name: Morebits QC

on:
  push:
    paths:
    - 'morebits.js'
    - 'tests/**'
    - 'package.json'
    - 'package-lock.json'
  pull_request:
    paths:
    - 'morebits.js'
    - 'tests/**'
    - 'package.json'
    - 'package-lock.json'

jobs:
  morebitsQC:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Morebits tests
      run: npm run test
